name: Tmate SSH

on:
  workflow_dispatch:

jobs:
  tmate:
    runs-on: ubuntu-latest

    steps:
      - name: Setup and Start tmate
        run: |
          sudo apt update
          sudo DEBIAN_FRONTEND=noninteractive apt upgrade -y
          sudo apt install -y tmate

          tmate new-session -d
          tmate wait tmate-ready

          echo "========================================"
          echo "SSH:"
          tmate display -p '#{tmate_ssh}'
          echo
          echo "Web:"
          tmate display -p '#{tmate_web}'
          echo "========================================"

          while true; do
            sleep 60
          done
